name: ❓ Question
description: Ask a question about one of our samples
labels: ['Needs: Triage :mag:', 'type:question']
title: "[question]: "
body:
- type: markdown
  attributes:
    value: |
      Thank you for asking a question! Use the sections below to submit a question **only** if its relates to this repository.. 
      
      - Questions that do not follow the below template will automatically be closed
      - Don't use questions to diagnose issues with samples, that's what [bug reports](https://github.com/pnp/powerfx-samples/issues/new?assignees=&labels=Needs%3A+Triage+%3Amag%3A%2Ctype%3Abug-suspected&template=bug-report.yml) are for!
      - All questions are welcome - let us know what's on your mind!
      - This repository is maintained voluntarily. Please be courteous and patient. 🙂
      - Remember to include sufficient details and context.
      - If you have multiple questions please submit them separately so we can track resolution.
      - Screenshots are always helpful (just paste any images right here in the question)
      - If you're trying to start a conversation on a topic, consider using [Discussions](https://github.com/gianlucaborelli/VillaBeach-WebService/discussions). We want to close every issue as quickly as possible, but discussions are intended for longer conversations.
- type: textarea
  id: question
  attributes:
    label: Question
    description: What would you like to know?
    placeholder: The more details, the better
  validations:
    required: true
