name: 💡 Suggestion
description: Suggest an enhancement to make one of our  samples even better
labels: ['Needs: Triage :mag:', 'type:enhancement']

body:
- type: markdown
  attributes:
    value: |
      Thank you for your suggestion! Use the sections below to submit a suggestion **only** if its relates to this repository. 
      
      - Suggestions that do not follow the below template will automatically be closed
      - All ideas are welcome - let's build something together!
      - This repository is maintained voluntarily. Please be courteous and patient. 🙂
      - Remember to include sufficient details and context.
      - If you have multiple suggestions please submit them separately so we can track resolution.
      - Screenshots are always helpful (just paste any images right here in the suggestion)
      
- type: textarea
  id: suggestion
  attributes:
    label: Suggestion
    description: What would you like to see improved?
    placeholder: The more details, the better
  validations:
    required: true
